[package]
name = "rerast"
version = "0.1.95"
license = "Apache-2.0"
description = "An AST (abstract syntax tree) based search replace tool for code written in Rust"
repository = "https://github.com/google/rerast"
readme = "README.md"
categories = ["development-tools", "development-tools::cargo-plugins"]
edition = "2018"
authors = [
    "David Lattimore <dvdlttmr@gmail.com>",
    "Dale Wijnand",
    "Kornel",
]

[dependencies]
rerast_macros = { version = "0.1.12", path = "rerast_macros" }
itertools = "0.9.0"
clap = "2.33.0"
json = "0.12.4"
diff = "0.1.12"
colored = "1.9.3"
failure = "0.1.8"

[dev-dependencies]
predicates = "1.0.4"
assert_cmd = "1.0.1"
